"""change tables

Revision ID: 07e7546c8273
Revises: 455b02657513
Create Date: 2025-10-02 05:24:53.652082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07e7546c8273'
down_revision: Union[str, None] = '455b02657513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_order', sa.Column('location', sa.String(), nullable=True))
    op.drop_column('service_order', 'total_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_order', sa.Column('total_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('service_order', 'location')
    # ### end Alembic commands ###
