"""change tables

Revision ID: 36452792b8eb
Revises: bf9b855eb104
Create Date: 2025-10-01 22:38:50.498131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36452792b8eb'
down_revision: Union[str, None] = 'bf9b855eb104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_order_item_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_order_item_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['service_order_item_id'], ['service_order_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_order_item_document_id'), 'service_order_item_document', ['id'], unique=False)
    op.alter_column('service_order', 'total_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.add_column('service_order_item', sa.Column('notes', sa.String(), nullable=True))
    op.drop_column('service_order_item', 'unit_value')
    op.drop_column('service_order_item', 'quantity')
    op.drop_column('service_order_item', 'total_value')
    op.add_column('service_type', sa.Column('icon', sa.String(), nullable=False, server_default='pi-circle-off'))
    op.alter_column('service_type', 'icon', server_default=None)
    op.alter_column('user', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('service_type', 'icon')
    op.add_column('service_order_item', sa.Column('total_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('service_order_item', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('service_order_item', sa.Column('unit_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('service_order_item', 'notes')
    op.alter_column('service_order', 'total_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_index(op.f('ix_service_order_item_document_id'), table_name='service_order_item_document')
    op.drop_table('service_order_item_document')
    # ### end Alembic commands ###
