"""change tables

Revision ID: 42ff55ed49ca
Revises: 36452792b8eb
Create Date: 2025-10-02 03:58:56.010339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42ff55ed49ca'
down_revision: Union[str, None] = '36452792b8eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('service_order_service_type_id_fkey', 'service_order', type_='foreignkey')
    op.drop_column('service_order', 'service_type_id')
    op.add_column('service_order_item', sa.Column('service_type_id', sa.Integer(), nullable=False, server_default="1"))
    op.alter_column('service_order_item', 'service_type_id', server_default=None)
    op.create_foreign_key(None, 'service_order_item', 'service_type', ['service_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_order_item', type_='foreignkey')
    op.drop_column('service_order_item', 'service_type_id')
    op.add_column('service_order', sa.Column('service_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('service_order_service_type_id_fkey', 'service_order', 'service_type', ['service_type_id'], ['id'])
    # ### end Alembic commands ###
