"""change tables

Revision ID: 455b02657513
Revises: 42ff55ed49ca
Create Date: 2025-10-02 04:15:42.991313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '455b02657513'
down_revision: Union[str, None] = '42ff55ed49ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_order_item', sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'FINISHED', 'CANCELED', name='serviceorderstatusenum'), nullable=False, server_default="PENDING"))
    op.alter_column('service_order_item', 'status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_order_item', 'status')
    # ### end Alembic commands ###
