"""add enum

Revision ID: 6a9a6438c350
Revises: c1a58d704b56
Create Date: 2025-11-02 21:06:12.034678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a9a6438c350'
down_revision: Union[str, None] = 'c1a58d704b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE documentsopositionenum AS ENUM ('BEFORE', 'AFTER')")
    op.add_column('service_order_item_document', sa.Column('position', sa.Enum('BEFORE', 'AFTER', name='documentsopositionenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_order_item_document', 'position')
    # ### end Alembic commands ###
