"""change tables

Revision ID: 84e3bafb0e21
Revises: 07e7546c8273
Create Date: 2025-10-02 08:13:44.360014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84e3bafb0e21'
down_revision: Union[str, None] = '07e7546c8273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_client_cnpj', table_name='client')
    op.drop_index('ix_client_email', table_name='client')
    op.create_unique_constraint(None, 'client', ['email'])
    op.create_unique_constraint(None, 'client', ['cnpj'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client', type_='unique')
    op.drop_constraint(None, 'client', type_='unique')
    op.create_index('ix_client_email', 'client', ['email'], unique=False)
    op.create_index('ix_client_cnpj', 'client', ['cnpj'], unique=False)
    # ### end Alembic commands ###
