"""remove column

Revision ID: ed5e9b009e10
Revises: 440629e9e821
Create Date: 2025-11-02 23:59:46.599183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed5e9b009e10'
down_revision: Union[str, None] = '440629e9e821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_order', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_order', sa.Column('status', postgresql.ENUM('PENDING', 'IN_PROGRESS', 'FINISHED', 'CANCELED', name='serviceorderstatusenum'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
